Lorem =["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget nisi pretium, ornare purus in, rhoncus lacus. Praesent id purus gravida eros ultricies placerat. Aenean semper nunc vitae augue efficitur pharetra. Morbi elementum massa a purus finibus mattis. Suspendisse mi neque, consequat eu rutrum ut, vehicula sit amet ligula. In nunc diam, fermentum vel leo vel, porttitor vestibulum est. Vestibulum egestas libero sapien, eget facilisis velit aliquam ut. Nam faucibus, ante in  tempus lacinia, ipsum risus lacinia urna, eu fringilla enim ipsum at sem. Integer facilisis mauris et lorem varius, ac varius ex pellentesque. Etiam consequat eget turpis et rhoncus.",
       "Proin at erat viverra, porttitor elit et, molestie massa. Nunc at porta nulla. Mauris commodo, velit eu volutpat egestas, mi enim facilisis erat, et vulputate metus nisl in lacus. Aliquam ac ornare risus. Pellentesque egestas, dui quis ultricies mollis, eros ante interdum ex, eu tristique tortor odio eu est. Phasellus vehicula velit sapien, id elementum mauris laoreet eget. Donec euismod lectus at ante lacinia ultrices id in ante. Donec efficitur porta hendrerit. Cras condimentum dapibus velit, eu maximus nibh convallis eget. Mauris lobortis metus in libero luctus sodales. Mauris ac fringilla tortor.",
       "Pellentesque est tellus, dapibus eu egestas sit amet, sagittis eu felis. Curabitur tortor nunc, pulvinar et facilisis quis, mattis tempor lacus. Praesent fringilla orci sed est tincidunt, eu condimentum enim dignissim. Phasellus aliquam luctus tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus at dictum urna, vitae scelerisque nunc. Ut id tellus eu turpis suscipit fermentum a at sem. Quisque eros ex, varius facilisis volutpat a, varius et ligula. Nam nec urna non velit suscipit congue. Duis malesuada magna bibendum, cursus risus sit amet, congue libero. Donec eget ligula dolor. Nam tristique eu justo in consequat. Mauris sed tincidunt odio. Vestibulum eget dictum enim, nec consequat nulla.",
       "Donec nisl sapien, blandit eu elit sit amet, pretium varius felis. Morbi convallis risus eget leo iaculis, sed faucibus erat convallis. Sed elementum tellus magna, eu cursus quam imperdiet cursus. Fusce neque risus, semper non neque eget, aliquam pulvinar justo. Nam sit amet magna vitae odio commodo molestie vitae id nisi. Fusce fringilla egestas enim a rhoncus. Curabitur pulvinar commodo nisl sed sagittis. Vestibulum ullamcorper faucibus neque at imperdiet. Nam quis dui feugiat, scelerisque augue ac, cursus nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris et rutrum odio. Aliquam feugiat ante efficitur, vestibulum dui nec, iaculis neque. Sed facilisis egestas porttitor.",
       "Proin dignissim maximus est vitae mattis. Cras in viverra sem. Nulla gravida lectus sit amet eros vulputate pharetra. Sed enim orci, cursus ac lectus vitae, ornare interdum lacus. Etiam tempus arcu sit amet lacus dapibus, a vulputate urna rutrum. Nam convallis ac risus ut ultrices. Ut luctus dapibus ex, ac vulputate massa bibendum et. Etiam metus ex, cursus vitae venenatis lobortis, vestibulum semper ligula. Cras et massa eu lectus vulputate condimentum. Donec feugiat erat vitae congue sagittis. Donec ultrices eros et dolor bibendum gravida. Ut blandit velit neque, nec efficitur quam bibendum nec. Phasellus metus magna, lobortis nec felis non, pellentesque vulputate orci. Quisque mollis fermentum justo, quis vulputate sapien pulvinar ac. Fusce bibendum ornare mauris at mollis. Etiam in urna odio.",
       "In quis enim metus. Aliquam quis tempus metus. Etiam ut tellus vel elit sagittis facilisis ut sit amet neque. Nunc sed velit lobortis sem finibus rhoncus. Suspendisse et ex massa. Duis quis sapien in libero lacinia consequat. Sed et tellus aliquet, accumsan magna vitae, ultricies erat. Maecenas non eleifend risus, egestas scelerisque ex. Suspendisse eros est, mollis ut consectetur quis, fermentum quis metus. Sed eu nibh porta, placerat odio in, congue lacus. Nulla sed vulputate nisi. Vivamus in volutpat urna. Quisque quis elementum urna. Nam at tortor blandit, mollis est sed, lacinia dolor.",
       "Sed euismod finibus leo vel posuere. Etiam convallis commodo dolor, eu efficitur arcu pulvinar at. Suspendisse nunc sem, interdum sed elit eu, vestibulum vehicula tortor. Duis iaculis posuere vestibulum. Vestibulum at pellentesque leo. Nunc viverra, nibh id fringilla auctor, purus arcu dignissim nulla, sed dapibus lacus quam vitae lorem. Quisque id ex et lorem ultrices feugiat id viverra orci.",
       "Sed bibendum sem et nulla lobortis, vitae placerat nulla porttitor. Donec nec convallis mauris. Duis placerat consequat odio ut consectetur. In iaculis pretium tristique. Proin vel felis venenatis nisi pharetra vehicula eget eu orci. Mauris consectetur et risus sed tincidunt. In ullamcorper augue in dictum eleifend. Praesent gravida condimentum feugiat. Phasellus condimentum ipsum et enim porttitor faucibus. Cras vitae gravida sem. Aliquam ultrices quam massa, quis semper enim scelerisque et. Nam placerat dignissim sapien sit amet laoreet. Etiam nec sapien interdum, pellentesque ex id, auctor velit.",
       "Ut sed nisi pellentesque, facilisis libero sit amet, condimentum magna. Nulla et diam pulvinar, consectetur eros sit amet, vestibulum nisl. Nullam facilisis, nibh a bibendum tempus, diam arcu pellentesque lorem, sit amet fermentum augue massa eu eros. Sed mattis magna malesuada tortor tempus pulvinar. Sed lacinia, diam a sollicitudin egestas, est urna mollis lorem, id molestie turpis ex eget libero. Duis fringilla, lorem eget vehicula pretium, velit eros faucibus enim, quis auctor diam purus ut eros. Morbi congue placerat nunc id porta. Ut erat erat, placerat non nisl eu, malesuada euismod turpis. Curabitur ut sapien sit amet odio porttitor consectetur nec non mauris. Quisque viverra ullamcorper nunc, in eleifend purus feugiat vel. Proin accumsan tortor vitae lorem tincidunt, nec ultricies nisi dignissim. Nam laoreet massa nec justo faucibus, sed iaculis neque vulputate. Fusce sodales nibh ante.",
       "Nulla libero risus, dapibus sit amet imperdiet tristique, vulputate quis magna. Donec finibus, ligula ac auctor lobortis, tortor nunc vulputate erat, sit amet suscipit urna lorem eget sapien. Maecenas vestibulum est urna, in luctus nulla tempus nec. Aenean aliquam tincidunt felis, in lacinia est convallis quis. Cras pulvinar commodo ipsum vitae ornare. Nunc rhoncus ultricies dui id tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam id ligula volutpat urna faucibus congue sit amet et mauris. Duis ex augue, consequat quis nulla non, maximus bibendum arcu. Nullam eleifend dapibus leo, sed tristique lorem suscipit quis.",
       "In nisl justo, ullamcorper et tincidunt eget, hendrerit congue erat. Nulla in ante nisl. Nam vel maximus nisl. Sed gravida est et risus vestibulum hendrerit. Nam bibendum, sapien sed sodales sodales, risus massa ultricies lacus, at feugiat felis nulla in nulla. Maecenas turpis mi, luctus ac interdum sed, porta quis lacus. Nam cursus elit nec lectus rutrum molestie. Sed maximus tellus sapien, vel pretium orci molestie non. Fusce nec maximus justo. Cras rutrum ipsum quis elementum sollicitudin. Vivamus rutrum felis sed nisi aliquam, dapibus ullamcorper nisl condimentum. Curabitur tincidunt ut lorem ac tincidunt. Suspendisse eu imperdiet odio.",
       "Nullam gravida erat nulla, sit amet aliquet lectus suscipit sit amet. Praesent dictum facilisis nibh, sed gravida dolor blandit quis. Nulla dictum erat eu eleifend bibendum. In sit amet vehicula mauris. Donec vel commodo velit. Integer lobortis urna purus, ac placerat lorem gravida ut. In blandit et quam ut posuere. Quisque quis dictum velit. Mauris nulla felis, faucibus non dictum eget, venenatis sit amet dui. Vivamus faucibus ornare convallis. Maecenas lacinia a urna sagittis dapibus. Sed leo enim, dignissim ut enim et, eleifend malesuada dolor. Nunc ut tempus ex.",
       "Sed euismod in felis non bibendum. Praesent non scelerisque odio, a tempus neque. Nunc semper condimentum scelerisque. Vivamus sollicitudin augue id metus viverra auctor. Integer quam diam, dapibus et dignissim id, accumsan dapibus risus. Quisque mollis sapien eu elit varius varius. Duis scelerisque erat et erat eleifend, vel consectetur lacus egestas. Ut lectus purus, maximus sit amet facilisis sit amet, ullamcorper nec quam. Fusce dignissim ante a metus porttitor malesuada eget nec elit. Cras molestie enim est, in semper lectus faucibus sit amet. Morbi sollicitudin turpis dolor, vitae dapibus dui blandit in. In orci est, pellentesque eget sem congue, eleifend blandit felis. Integer vel vestibulum odio. Vivamus maximus mollis diam quis imperdiet. Praesent in augue vitae arcu commodo pretium. Curabitur hendrerit a neque non pharetra.",
       "Nam tincidunt enim quis massa tempor, id vulputate tellus ornare. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin rhoncus tempus commodo. Curabitur risus nisi, viverra eget leo ac, vestibulum dignissim tortor. Donec vel fermentum lorem. Suspendisse semper vehicula nibh, eu facilisis nisi accumsan sit amet. In eu diam ligula. Phasellus ullamcorper, orci at dictum tincidunt, elit arcu efficitur est, a eleifend nisl lacus vitae quam. Vestibulum eu pharetra quam. Phasellus fermentum, justo sed mattis venenatis, eros arcu faucibus orci, a sodales orci elit eget purus. Integer eu posuere augue.",
       "Integer bibendum pellentesque orci, ut fringilla ante condimentum blandit. Nam elementum non erat vel imperdiet. Nulla at metus vitae enim finibus luctus. Vivamus ac ligula velit. Pellentesque quis sapien in leo faucibus aliquam in non ipsum. Nullam ligula augue, gravida eu porttitor eget, semper eu felis. Sed in congue lorem. Suspendisse consequat pulvinar ultrices. Aenean mollis placerat metus, in dapibus urna tempor sed. Ut sit amet tempus felis. Proin quis neque in mauris elementum bibendum eget et nisi. Vestibulum eu nisl et neque pellentesque euismod. Morbi at elementum augue. Aenean eu fermentum sapien, quis egestas ex. Morbi malesuada arcu vel eros vehicula, at pretium nulla interdum. Etiam non blandit nunc.",
       "Nullam magna leo, bibendum eget sollicitudin vel, finibus ac purus. Quisque blandit bibendum ex, quis dapibus lacus tincidunt eu. Etiam id nulla id erat lacinia condimentum vel vitae urna. Nunc pellentesque urna ut orci ultrices, et dignissim nunc mattis. Donec volutpat sem nec porttitor ornare. Duis at felis accumsan, placerat eros nec, gravida risus. Sed aliquam erat ut venenatis molestie. Sed a diam in lectus posuere finibus ut vitae arcu. Maecenas volutpat elit id nulla pellentesque rutrum sed sed est. Morbi id tristique justo. Sed nec dui et est aliquam porttitor. Sed ut libero velit. Mauris convallis quam odio, sed faucibus purus elementum at. Proin varius vitae diam non pharetra. Aliquam vitae tempus diam. Curabitur tincidunt leo sed libero bibendum aliquet.",
       "Sed in efficitur metus, sed placerat urna. Pellentesque est leo, interdum ut viverra sed, imperdiet sit amet eros. Nullam porta congue metus, vel fringilla velit condimentum et. Phasellus bibendum eros iaculis, sagittis orci ut, euismod mi. Nam massa erat, ullamcorper non placerat in, feugiat id turpis. Praesent aliquam, enim imperdiet consectetur suscipit, est orci luctus ligula, eget eleifend ipsum purus quis elit. Curabitur non nibh at odio dictum lobortis. Aenean nec massa massa.",
       "Morbi vel mollis quam, ultricies imperdiet mauris. Proin nec sem ex. Quisque eu nisi pretium, consectetur nulla et, imperdiet dui. Maecenas eleifend neque nec urna vestibulum tincidunt. Curabitur id quam et ex tincidunt tincidunt a sagittis neque. Vestibulum tincidunt sodales interdum. Ut sit amet porttitor ex. Nam id mollis urna, ut accumsan arcu. Ut quis ipsum non nibh mattis pulvinar id in eros. Donec ac tempus odio. Praesent eleifend tellus nec urna vulputate, at gravida orci sollicitudin. Aenean suscipit ornare ante eget convallis.",
       "Quisque at quam turpis. Proin egestas ultrices eleifend. Aliquam vitae malesuada lectus, id rutrum nibh. Cras non orci interdum, hendrerit turpis vitae, tristique ligula. Nam lacus risus, euismod non lobortis ac, scelerisque eget enim. Vestibulum et sapien sed nulla scelerisque feugiat. Vestibulum et magna in arcu suscipit accumsan congue a nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam et tellus a elit posuere ullamcorper. Vestibulum dui diam, aliquam a sapien sit amet, varius lobortis lacus. Praesent at ligula nulla. Duis suscipit pulvinar justo, at placerat ante interdum in. Mauris sit amet risus fermentum, rutrum neque efficitur, suscipit ipsum.",
       "Mauris non sodales quam. Morbi malesuada vitae sem pulvinar ultrices. Aliquam aliquam sagittis risus. Nulla ac lectus vitae nibh tincidunt tincidunt. Donec mattis libero quis ante fringilla, at aliquam dolor posuere. Mauris luctus neque eu est consequat gravida. Quisque cursus turpis vel cursus pulvinar. Curabitur dignissim tincidunt felis, id volutpat est convallis id. Nullam nec nisi sit amet turpis eleifend euismod. Curabitur volutpat nisl vel turpis molestie, vitae varius diam fermentum. Vivamus et felis a sapien commodo eleifend ac eget lectus. Nam consequat eu risus id egestas. Phasellus arcu nisl, elementum ut sem eu, faucibus malesuada sapien. Morbi dignissim quis lacus ac dictum. Nam sollicitudin vel elit a tincidunt.",
       "Nunc sed dolor tempus, vulputate nisi vel, pharetra urna. Fusce finibus eros vitae ante venenatis elementum. Maecenas in maximus dui, nec efficitur eros. Nulla eu arcu augue. Donec metus eros, euismod ut lacus a, tempus euismod purus. Cras sollicitudin nunc vitae elit pharetra, ut fermentum nisi porta. Pellentesque porta, arcu in finibus tempus, augue felis lobortis tortor, ut tristique elit sem id libero. Maecenas ultricies turpis ac eleifend mollis. Mauris aliquam lacus id tellus aliquet, quis pharetra diam elementum. Sed sed nisi tincidunt, ornare justo vitae, feugiat odio. Pellentesque posuere est vitae mauris rutrum, nec posuere tellus egestas.",
       "Quisque eu hendrerit risus, a euismod leo. Nam eget mi non dolor sodales dapibus ut eu lectus. Vivamus eu erat vestibulum, tincidunt tellus ut, mollis enim. Aenean enim nulla, sodales id enim eget, imperdiet euismod justo. Sed eget ullamcorper odio, eu semper quam. Suspendisse at felis fermentum, tincidunt erat ac, dapibus arcu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus consectetur velit quis velit convallis tincidunt. Nam elementum risus sit amet lectus sodales ultricies. Sed arcu justo, bibendum sit amet pharetra vel, vehicula vel dui. Aenean vel dapibus purus. Sed sodales mi lorem. Suspendisse scelerisque elementum sem, molestie accumsan lacus ultricies in. Vestibulum a ipsum laoreet, auctor lacus vel, mollis massa. Aenean tincidunt varius egestas.",
       "Mauris turpis orci, semper vitae volutpat et, placerat non nisl. Morbi sit amet iaculis lectus. Phasellus a orci at odio sagittis maximus. Praesent vehicula interdum mauris, ut posuere augue vehicula quis. Curabitur elementum risus a justo sagittis tempus. Integer tincidunt condimentum nibh, in porta turpis finibus et. Praesent mattis luctus faucibus. Donec eu sagittis leo. Aliquam rutrum justo a tortor rhoncus molestie sed et dui. Duis rutrum hendrerit rhoncus. Sed dignissim risus in nibh ullamcorper, consequat maximus neque dictum. Praesent hendrerit sodales imperdiet. Etiam ut nunc a orci mollis dapibus ornare et lectus. Suspendisse luctus ultrices sagittis.",
       "Cras porta est id laoreet vulputate. Donec sagittis condimentum nibh porta finibus. Maecenas ac mi vitae erat tempor feugiat. Morbi iaculis commodo est ac dignissim. Phasellus auctor lacinia tortor, id volutpat purus fermentum vel. Suspendisse dignissim pharetra lacus ut ornare. Suspendisse placerat non est semper dignissim. Quisque ac orci vestibulum, tempor metus in, vestibulum ligula. Curabitur sed fringilla purus. Praesent euismod eros eu orci scelerisque tempus quis ac quam. Nam accumsan sapien in odio convallis porta. Aenean elementum cursus malesuada. Sed orci enim, tempus eu nunc vitae, consequat elementum erat.",
       "Donec sagittis leo et ante tincidunt dapibus. Ut scelerisque lacus elit, non vehicula risus rhoncus nec. Nunc vel feugiat metus. Praesent in mi a eros tempus maximus ut vitae eros. Donec gravida gravida condimentum. Quisque ac leo ac arcu efficitur malesuada. Nam maximus turpis orci, vitae posuere tellus convallis eu. Donec mollis, erat eget accumsan commodo, erat quam volutpat quam, id laoreet tellus nunc sed dui. Fusce sit amet magna diam. Sed lorem nunc, pretium eget viverra non, auctor vitae libero. Quisque tincidunt ante nisi, vel ultricies lacus semper aliquam. Integer enim magna, sodales et enim quis, pulvinar posuere erat.",
       "Curabitur elementum lorem in porttitor bibendum. Praesent ullamcorper facilisis dolor at pretium. Mauris massa justo, accumsan at varius sed, tincidunt quis libero. Nulla et viverra turpis, et fermentum urna. Phasellus eu tempor felis. Suspendisse ultricies est libero, ut varius leo blandit sit amet. Suspendisse massa ex, ornare in lacus sit amet, commodo ultricies mi. Nunc mattis mauris sed elit egestas ultricies. Donec a efficitur odio. Cras ut scelerisque turpis. Praesent et odio a augue ultrices rhoncus. Curabitur sit amet mi semper, lobortis dolor sit amet, venenatis est. Sed porta iaculis lorem, vitae venenatis nulla.",
       "Mauris nunc orci, gravida quis magna eget, pulvinar porta mauris. Quisque nulla odio, condimentum suscipit accumsan quis, fringilla nec turpis. Nulla facilisi. Maecenas a massa vitae odio lacinia feugiat. Sed nibh nunc, tincidunt in erat sed, faucibus iaculis nisi. Morbi malesuada vitae sem sit amet dapibus. Nunc scelerisque magna sit amet rutrum mollis. Sed sed vulputate sapien. Nulla facilisi. Praesent ex tellus, malesuada sed commodo quis, efficitur at est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis convallis nisl leo, sagittis gravida risus bibendum et. Mauris consectetur mattis pharetra. Nulla metus nisi, iaculis dapibus convallis porttitor, venenatis vitae enim. Fusce eu enim est.",
       "Aenean ac vulputate risus, pulvinar faucibus neque. Sed auctor congue nisl, nec posuere nisi rhoncus at. Praesent lobortis non sem id ultricies. Nunc justo tortor, feugiat eget nisi ut, lacinia iaculis nisl. Fusce mollis faucibus convallis. Sed a est vel quam suscipit rhoncus quis ut nulla. Morbi scelerisque eget elit ut pulvinar. Proin sit amet pellentesque quam, a sodales ipsum. Etiam malesuada eget nunc ac fermentum. Cras metus velit, dictum a egestas non, pellentesque ultrices dolor.",
       "Duis aliquet felis sed orci aliquet bibendum. Cras fringilla sem et tincidunt cursus. Cras sit amet fringilla erat, vitae volutpat ex. Phasellus tincidunt sapien vel metus pulvinar luctus. Suspendisse pellentesque odio sem. Morbi nec feugiat tellus, et condimentum massa. Pellentesque molestie, nunc eu ultricies auctor, nisi massa pellentesque ante, et egestas elit metus at elit. Integer vel mi eget nibh commodo pulvinar id nec velit. Morbi consectetur est ac efficitur tincidunt. Morbi consectetur convallis lorem eu tincidunt. Cras euismod nisi a euismod imperdiet.",
       "Suspendisse pulvinar dapibus dolor sed imperdiet. Sed finibus consectetur nunc, at volutpat erat laoreet pellentesque. Donec ut orci ut eros volutpat rhoncus. Donec aliquet volutpat elit, nec mattis felis elementum convallis. Nulla molestie augue ante, et tempor felis sagittis non. Integer luctus lacinia facilisis. Maecenas condimentum odio et purus elementum, at placerat diam suscipit. Aenean suscipit, nunc sit amet venenatis finibus, arcu massa tempor orci, id semper mauris urna at sem. Proin ultricies metus nibh, vitae scelerisque dolor feugiat ac. Donec lobortis ultrices risus, ut pretium lorem efficitur quis. Fusce sed eros elementum, volutpat urna et, volutpat est. Ut eu pharetra sem, ut condimentum ex.",
       "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur magna nec tincidunt accumsan. In sit amet accumsan ligula, sodales sollicitudin est. Aenean tristique risus vel tristique elementum. Aenean consequat, libero ultrices blandit vehicula, enim augue condimentum libero, at elementum odio odio ut enim. Nunc finibus mollis ex, eu porta ligula iaculis id. Nam finibus consequat massa, eu viverra orci imperdiet quis. Pellentesque cursus erat ut pretium tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer vel imperdiet urna.",
       "Integer vitae auctor elit. Nam lobortis nibh ligula, quis commodo orci elementum at. Donec vel ultricies ante. Donec venenatis velit id pretium auctor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum fermentum neque ac diam tincidunt, in malesuada ex auctor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus suscipit tempus lacus, a finibus diam finibus at. Curabitur vulputate porta congue. Vivamus gravida arcu vel ligula sagittis, id consequat sapien dignissim. In et venenatis purus, id tempor ex.",
       "Sed odio nulla, volutpat vitae magna sit amet, ornare mollis nulla. Mauris et leo auctor, blandit tortor a, dignissim mauris. Suspendisse congue ultricies ex, quis auctor eros tincidunt vitae. Suspendisse convallis molestie felis, congue laoreet dui. Morbi id nibh a eros eleifend luctus. Quisque tristique consectetur turpis, eu tempor enim luctus non. Pellentesque quis dolor vel risus vehicula ultrices ut et nulla. Donec varius dapibus diam et iaculis. Morbi feugiat diam magna, eu sodales augue consequat ac. Nulla aliquam vel justo nec volutpat. Nunc sem eros, sodales vitae vehicula non, porttitor ac turpis. Sed vel odio quis lectus fermentum mattis non ac massa. Nullam in risus auctor, pellentesque magna id, malesuada purus. In sit amet tincidunt massa, sit amet auctor dolor. Proin cursus placerat sodales.",
       "Nam ullamcorper eget nisl eu tincidunt. Cras imperdiet nisl volutpat nisl iaculis, in iaculis tortor vehicula. Suspendisse eros ipsum, lacinia vel nisl non, porttitor pretium neque. In hac habitasse platea dictumst. Integer tempor, quam vitae bibendum suscipit, eros quam varius ipsum, nec ultrices mauris enim vitae eros. Vivamus id dignissim mi, vitae vulputate risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas et magna vel sapien consequat facilisis sit amet nec tellus. Nullam aliquet enim in leo suscipit elementum. Nulla sit amet porttitor massa. Nam purus lorem, eleifend in eros at, tincidunt ullamcorper velit. Aliquam non augue vitae justo malesuada varius quis a augue. Nulla ultricies ante at gravida consectetur. Morbi ac lacus cursus, molestie quam quis, tristique leo.",
       "Integer vel velit placerat, porta nunc porttitor, congue elit. Donec in rhoncus sem. Duis fermentum dolor ut consequat congue. Donec et odio euismod, fringilla lacus eget, vestibulum lorem. Aliquam lobortis odio ac massa elementum eleifend. Integer vitae lectus tempor risus faucibus facilisis. Etiam non finibus libero. Suspendisse pretium imperdiet tincidunt. Suspendisse potenti. Pellentesque volutpat augue ac ante volutpat blandit.",
       "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut pulvinar id nulla ut sollicitudin. Aliquam quam leo, sollicitudin et tristique sed, mollis nec turpis. Sed a eros diam. Cras at iaculis urna, nec viverra erat. Phasellus vulputate mauris sed porttitor elementum. Maecenas molestie dolor odio, sit amet aliquet neque fermentum pulvinar. Nullam ac ipsum sed ex tristique posuere. Suspendisse imperdiet sodales tortor. Pellentesque sit amet euismod felis, id dictum mauris. Morbi aliquam volutpat semper. Proin sit amet elementum enim. Aenean nec est dui. Nunc auctor varius posuere. Donec blandit ullamcorper dui, id sodales enim euismod vel. Duis hendrerit, mauris non fringilla congue, sem est placerat dui, ac lobortis velit metus scelerisque lectus.",
       "In hac habitasse platea dictumst. Integer auctor, lacus et mollis ullamcorper, lectus ante mollis sem, a euismod justo sem a ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce quis lectus volutpat, porttitor sapien sed, blandit urna. In pulvinar metus ligula, in tincidunt urna cursus tincidunt. Phasellus vel diam diam. Sed elementum arcu sed ipsum accumsan convallis ac quis ante. Praesent vehicula tristique urna.",
       "Quisque scelerisque nisi eget augue mollis varius. Vestibulum mattis rhoncus justo id suscipit. Nullam non gravida urna, sed iaculis sapien. Curabitur maximus erat libero, eu facilisis sapien bibendum nec. Nunc pharetra vestibulum suscipit. Maecenas maximus dui sit amet tellus tincidunt, vitae gravida justo sollicitudin. Duis facilisis, nulla nec pretium ultricies, est urna blandit augue, eu luctus felis tortor sed tortor. Aliquam nulla dolor, maximus eget lobortis sed, laoreet eu ipsum. Morbi eget ipsum mi. Maecenas pulvinar ornare nisi, id pharetra justo pellentesque sed. Nulla quam ipsum, maximus sed nisi quis, mattis tincidunt est.",
       "Curabitur imperdiet tortor et blandit faucibus. Donec sodales ullamcorper risus, in porttitor ante consectetur sed. Aenean sed eros nisi. Suspendisse vitae egestas nisi, volutpat commodo neque. Nunc non nisl convallis, imperdiet neque a, ullamcorper ipsum. Pellentesque massa elit, placerat in varius sed, sodales a nisi. Curabitur fringilla lobortis eleifend. Nulla molestie iaculis augue at porttitor. Cras a porta libero.",
       "Integer ullamcorper nunc non lacus ultricies iaculis. Quisque finibus neque tellus, vel varius enim efficitur sit amet. Donec fringilla mauris eu lobortis aliquam. Morbi non risus maximus, eleifend nisi a, congue mauris. Etiam in volutpat justo, eu hendrerit augue. Pellentesque efficitur nibh at urna condimentum tincidunt. Etiam eget luctus nibh, a scelerisque magna. Maecenas vehicula, eros non blandit pharetra, sem odio eleifend augue, non volutpat nibh tortor et ex. Ut a magna mollis, ornare nunc vel, feugiat orci. Nullam non sem ac lorem ornare ornare in vel ipsum. Duis vel magna congue justo commodo consequat. Praesent dapibus sem quis sapien faucibus venenatis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus fringilla porttitor nulla nec aliquet. Morbi quis tincidunt nisi.",
       "Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin rhoncus augue turpis, at vulputate nunc finibus quis. Pellentesque dui leo, consequat ut dignissim ut, venenatis eget nisl. Donec eu velit sodales, facilisis nibh eu, fringilla tellus. Vestibulum porttitor, leo a feugiat aliquam, metus enim venenatis metus, nec finibus leo felis non mi. Duis volutpat sem non fermentum viverra. Proin nulla augue, rutrum quis luctus nec, accumsan sit amet nulla. Donec in lectus id leo suscipit facilisis sit amet quis ante. Nunc non turpis erat. Vivamus leo mi, cursus eget erat vitae, sodales vestibulum sapien. Proin in est id dui vestibulum pretium. In quis leo vitae tellus molestie fringilla.",
       "Nam ullamcorper nibh nec augue luctus sagittis. Vestibulum faucibus est at massa venenatis tincidunt in nec massa. Nunc vulputate enim ut nisi suscipit, et blandit augue tincidunt. Donec eu velit et turpis tincidunt aliquam vitae feugiat justo. Sed malesuada mattis ligula ac hendrerit. Cras in dui vel nisl placerat dignissim in a nunc. Phasellus vehicula sem arcu, nec rutrum arcu dapibus in. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras sem ligula, porta sit amet odio nec, viverra sodales mauris. Fusce eu ipsum sit amet orci viverra pellentesque. Vestibulum non sem lacus. Quisque cursus porta elit quis vulputate. Vivamus nec varius quam. Nunc congue lobortis euismod. Integer maximus sem magna, sit amet feugiat purus volutpat nec. Etiam luctus, eros ut vulputate ultrices, massa massa pharetra leo, a ullamcorper tellus odio at dolor.",
       "Aliquam semper leo id porttitor euismod. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam placerat luctus maximus. Cras non elit hendrerit, lobortis mi eget, vulputate leo. Nullam fermentum, elit vel blandit tincidunt, justo augue efficitur neque, quis imperdiet justo mi ut nunc. Mauris eget tortor sit amet nulla elementum luctus. Donec vitae leo nulla. Vestibulum condimentum dui vitae tortor luctus hendrerit. Vivamus et orci efficitur, feugiat turpis ut, scelerisque odio. Nullam dictum lorem at ligula consectetur aliquam. Sed auctor neque vel vestibulum suscipit. Vivamus rhoncus magna in lectus finibus, sed lobortis massa ullamcorper. Curabitur at purus orci. Morbi fermentum nibh id euismod euismod.",
       "Phasellus sed odio ornare, sagittis enim ac, pulvinar lorem. Proin sit amet odio augue. Sed tempor et erat id pellentesque. Pellentesque in eleifend nisi. Aenean pellentesque elit non dolor vulputate, eu ultrices magna tempus. Quisque a blandit lorem. Integer pulvinar enim vitae aliquet convallis.",
       "Morbi a placerat diam. Ut vestibulum pellentesque lobortis. Vestibulum sit amet euismod massa. Curabitur risus ante, pharetra at condimentum ac, aliquam ut massa. Fusce non nulla et nulla semper imperdiet. Aenean ut risus nec ligula tristique efficitur quis eget libero. In metus erat, hendrerit et tempus eget, pulvinar ut nibh. Duis lorem eros, vulputate quis eleifend condimentum, fringilla id est. Ut malesuada pretium justo a condimentum. Morbi a justo quis mauris maximus finibus pulvinar laoreet felis. Donec imperdiet, justo tempus venenatis venenatis, felis sapien fringilla urna, gravida elementum turpis ex ullamcorper nibh. Vestibulum vel imperdiet neque. Praesent fringilla erat eget nunc tempor, sed sodales tellus vestibulum.",
       "Sed vitae tellus vitae urna feugiat pharetra id ut felis. Sed cursus non mauris eu fringilla. Nullam interdum eget arcu sit amet tempor. Integer vulputate mauris nec odio rhoncus consequat. Fusce id blandit ligula. Nullam eu hendrerit ligula. Maecenas hendrerit egestas nibh eget vehicula. Etiam sagittis consectetur ligula, sed vehicula ex ullamcorper sit amet. Nullam faucibus vel leo sit amet dignissim. Aenean enim dui, posuere eu leo sit amet, accumsan porta odio. Aenean quis tristique lectus. Mauris condimentum, tellus eget ultricies pellentesque, ante lectus mattis ipsum, id lobortis nibh justo sit amet lorem. Morbi vel euismod metus. Donec urna turpis, bibendum eget faucibus ut, posuere in est. Sed ullamcorper vulputate enim sed porttitor.",
       "Aliquam eget sapien felis. Praesent leo est, congue sed ipsum ac, venenatis mollis purus. Donec non ultricies dolor, vel ultricies dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis vehicula laoreet sem id volutpat. Pellentesque tempor libero bibendum scelerisque viverra. Vestibulum luctus quam eu nulla varius tincidunt. Mauris nec imperdiet ex. Suspendisse ut nibh vel ligula ultricies posuere.",
       "Nunc maximus nulla finibus, eleifend lorem ultrices, euismod odio. Quisque imperdiet nisi vitae vulputate imperdiet. Cras mollis, elit quis facilisis blandit, magna ligula rutrum odio, eu sollicitudin odio lorem et quam. Quisque ac ligula egestas, congue sapien in, ultrices sapien. Mauris nec eros egestas leo feugiat vestibulum at nec metus. Nullam et diam faucibus, accumsan leo ut, viverra felis. Aenean quis efficitur sem, vel finibus tellus. Etiam id diam vitae dolor bibendum porta. Suspendisse potenti. Maecenas a turpis est. Maecenas luctus in nisi non sagittis. Maecenas aliquet aliquam tincidunt. Pellentesque lectus enim, interdum id leo vitae, pulvinar tincidunt ipsum.",
       "Mauris auctor ultricies tempus. Donec a arcu eu nisi molestie fermentum. Suspendisse at nisl sed magna rhoncus consectetur. Morbi eu convallis purus. Sed vel facilisis mauris, vel semper dolor. Pellentesque pretium et ligula non maximus. Pellentesque nisi felis, euismod nec sapien non, laoreet sodales est. Curabitur dictum nunc eu felis sollicitudin, non ultricies lacus egestas. Nullam molestie risus ut tortor gravida semper. Nulla congue maximus pellentesque. Nunc aliquet lorem tristique tortor feugiat, eu dapibus neque tempor. Nullam gravida, mauris id auctor fermentum, libero magna sollicitudin diam, nec tempor ante orci in ante. Phasellus et tortor a arcu pellentesque dapibus.",
       "Quisque varius urna tellus, nec pulvinar tellus porta sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur dictum, orci in eleifend cursus, velit quam commodo nibh, nec egestas sem magna in leo. Phasellus facilisis, nibh id pretium mollis, ipsum justo egestas est, in aliquam leo nibh ut nisl. Pellentesque non tortor quis nisi posuere maximus tempor eget magna. Mauris ac nunc congue, consectetur lorem hendrerit, euismod justo. Phasellus lectus libero, auctor vitae felis hendrerit, tincidunt lobortis ex. Quisque porttitor semper rutrum. Nulla a erat commodo, tincidunt purus nec, gravida diam. Pellentesque id orci vitae ligula iaculis pharetra. Quisque sed dictum ipsum. Maecenas sem sapien, posuere vel fringilla sit amet, semper quis dolor. Pellentesque ut placerat lectus. Donec vitae mauris nulla. In a nisl nunc. Nam maximus ipsum massa, egestas sodales mauris fringilla sed."]

       def is_number(number)
           if number.match(/^-?(\d|[1-9]+\d*|\.\d+|0\.\d+|[1-9]+\d*\.\d+)$/) == nil
               return false
           end
           return true
       end

       #Validar cantidad de parametros
       if ARGV.length != 1
           puts "ERROR: Se requiere 1 parametro"
           exit
       end

       #validar que sean float
       numeros=[]
       for i in ARGV
           if !is_number(i)
               puts "ERROR: El parametros debe ser numericos"
               exit
           end
           numeros.push(i.to_f)
       end

       parrafos = numeros[0].to_i
       parrafos.times { |i| puts "#{Lorem[i]}" }
